### ISSUE TITLE
[VS code] svg 태그

### ISSUE THREAD

**Issue by wuixwui** [JayoonKoo/soylent-clone#14]
![image](https://user-images.githubusercontent.com/78251048/127609243-1cdfdc16-fa42-46e5-bb65-8a0c0bc460b6.png)

svg 태그 밑으로 태그 컬러가 변하는데 혹시 저만 그런건가요?

**Comment by kimyerimweb** [comment]
![스크린샷 2021-07-30 오후 5 01 49](https://user-images.githubusercontent.com/77137382/127621493-a00824ca-732b-4f6d-a746-a60364944269.png)
저는 material theme이라는 확장 프로그램으로 덮어버려서 이렇게 나와요! 별문제는 없습니다. 혹시 svg 태그 위쪽이랑 태그랑 내용 색이 다르신가요?

**Comment by kimyerimweb** [comment]
앗...material theme 꺼놓고 다시 봤는데 대참사가..ㅋㅋ.....시각테러 죄송합니다ㅠㅠ 강렬하네요...ㅋㅋㅋ...이거 svg 태그 오른쪽 꺽쇠가 안붙어있어서 오류라고 뜨는 것 같습니다. 수정해서 다시 올릴게요ㅠㅠ

**Comment by wuixwui** [comment]
47번 줄 menu button 뒤쪽에 `"`하나가 빠져있어요!

**Comment by kimyerimweb** [comment]
앗 그러네요..! 혹시 지금 하고 계신 중이라면 수정 부탁드려도 될까요? 나중에 한번에 머지해서 right부터 할까하네요

**Comment by wuixwui** [comment]
우선 제 로컬에는 수정해 두었습니다!
천천히 하셔도 돼요! 

전 우선 스타벅스 클론 드롭 하구 있을게요...! 😍
